.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,32 +8,29 @@ on: #this workflow runs on pull requests and pushes to main or master
 
 #this is a list of all jobs
 jobs:
-  check-main-latest-commit:
+  check-main-merged-in-pr:
     runs-on: ubuntu-latest
-    outputs:
-      is_up_to_date: ${{ steps.check-commit.outputs.is_up_to_date }}
     steps:
       - name: Checkout the repository
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      - name: Check if PR is up-to-date with main's latest commit
-        id: check-commit
+      - name: Check if main is merged into PR branch
         run: |
           git fetch origin main
-          LATEST_MAIN_COMMIT=$(git rev-parse origin/main)
-          LATEST_PR_COMMIT=$(git rev-parse HEAD)
+          MAIN_COMMIT=$(git rev-parse origin/main)
+          PR_COMMIT=$(git rev-parse HEAD)
 
-          if [ "$LATEST_MAIN_COMMIT" != "$LATEST_PR_COMMIT" ]; then
-              echo "Error: The PR branch is not up-to-date with the latest commit in the main branch."
-              exit 1
+          if git merge-base --is-ancestor $MAIN_COMMIT $PR_COMMIT; then
+              echo "The PR branch is up-to-date with the main branch."
           else
-              echo "The PR branch is up-to-date with the latest commit in the main branch."
+              echo "Error: The PR branch is not up-to-date with the main branch."
+              exit 1
           fi
   linting:
     runs-on: ubuntu-latest
-    needs: check-main-latest-commit
+    needs: check-main-merged-in-pr
     steps:
       - name: Checkout #checks out our current branch so this runner has the latest code
         uses: actions/checkout@v4 #uses means that it is a pre-defined action supplied by GitHub.
@@ -52,7 +49,7 @@ jobs:
 
   testing: #name of first job
     runs-on: ubuntu-latest #sets the env which this job runs on
-    needs: [linting, check-main-latest-commit]
+    needs: [linting, check-main-merged-in-pr]
     steps: #defines the steps necessary
       - name: Checkout #checks out our current branch so this runner has the latest code
         uses: actions/checkout@v4 #uses means that it is a pre-defined action supplied by GitHub.
