added a test workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,6 +8,21 @@ on: #this workflow runs on pull requests and pushes to main or master
 
 #this is a list of all jobs
 jobs:
+  check-main-merge-status:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Check if up-to-date with main branch
+        run: |
+          git fetch origin main:main
+          DIFF=$(git diff --name-only HEAD main)
+          if [ "$DIFF" ]; then
+              echo "Error: Branch is not up-to-date with main. Please merge the latest main into your branch."
+              exit 1
   linting:
     runs-on: ubuntu-latest
     steps:
@@ -42,3 +57,62 @@ jobs:
 
       - name: Run tests #if npm test throws and error this workflow fails.
         run: npm test
+
+        ## TESTING WORKFLOW:
+
+        # name: Linting, Prettier, Testing, and Branch Check
+# on:
+#   pull_request:
+#     branches: [main, master, test-branch]
+#   push:
+#     branches: [main, master, test-branch]
+#   workflow_dispatch:
+
+# jobs:
+#   check-main-merge-status:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout the repository
+#         uses: actions/checkout@v4
+#         with:
+#           fetch-depth: 0
+
+#       - name: Check if up-to-date with main branch
+#         run: |
+#           git fetch origin main:main
+#           DIFF=$(git diff --name-only HEAD main)
+#           if [ "$DIFF" ]; then
+#               echo "Error: Branch is not up-to-date with main. Please merge the latest main into your branch."
+#               exit 1
+
+#   linting:
+#     runs-on: ubuntu-latest
+#     needs: check-main-merge-status
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v4
+#       - name: Setup Node
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: 20
+#       - name: NPM Install
+#         run: npm ci
+#       - name: Run linting
+#         run: npm run lint
+#       - name: Run prettier
+#         run: npm run prettierW
+
+#   testing:
+#     runs-on: ubuntu-latest
+#     needs: linting
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v4
+#       - name: Setup Node
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: 20
+#       - name: NPM Install
+#         run: npm ci
+#       - name: Run tests
+#         run: npm test
